version: "3.9"

services:
  node-server:
    image: dimitridr/skyhub-server:latest
    container_name: SkyHub
    ports:
      - "4000:4000"
  mongodb:
    image: mongo:latest
    container_name: MongoDB
    ports:
      - "27017:27017"