openapi: '3.0.2'
info:
  title: SkyHub API
  description: API permettant de récupérer diverses données (fictives) sur l'aviation.
  version: '0.0.2'
  license:
    name: Licence MIT
    url: https://opensource.org/licenses/MIT

servers:
  - url: http://localhost:4000
    description: Serveur local

tags:
  - name: flights
    description: Opérations liées aux vols
  - name: airports
    description: Opérations liées aux aéroports

paths:
  /api/airports:
    # QA passed
    get:
      summary: Récupérer la liste complète des aéroports
      tags:
        - airports
      parameters:
        - in: query
          name: id
          required: false
          description: Identifiant unique de l'aéroport.
          schema:
            type: integer
            example: 10165
        - in: query
          name: city
          required: false
          description: Ville où se situe l'aéroport.
          schema:
            type: string
            example: Barrow
        - in: query
          name: state
          required: false
          description: Code ISO 3166-2 (moins le préfixe « US- ») de l'état où se situe l'aéroport.
          schema:
            type: string
            example: CA
        - in: query
          name: name
          required: false
          description: Nom de l'aéroport.
          schema:
            type: string
            example: San Francisco International
      responses:
        '200':
          description: Une liste de tous les aéroports enregistrés.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Airport'
    # QA passed
    post:
      summary: Ajouter un aéroport
      tags:
        - airports
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                city:
                  type: string
                  description: Ville où se situe l'aéroport.
                  example: Washington
                state:
                  type: string
                  description: Code ISO 3166-2 (moins le préfixe « US- ») de l'état où se situe l'aéroport.
                  example: DC
                name:
                  type: string
                  description: Nom de l'aéroport.
                  example: Washington Airport
              required:
                - city
                - state
                - name
      responses:
        '201':
          description: L'aéroport a été ajouté avec succès.
          content:
            application/json:
              schema:
                type: object
                properties:
                  city:
                    type: string
                    example: Washington
                  state:
                    type: string
                    example: DC
                  name:
                    type: string
                    example: Washington Airport
                  _id:
                    type: integer
                    example: 93999209
        '400':
          description: Requête invalide ou erreur critique côté serveur.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Erreur retournée par le serveur : [message d'erreur]."
  /api/airports/{id}:
    # QA passed
    delete:
      summary: Supprimer un aéroport
      tags:
        - airports
      parameters:
        - in: path
          name: id
          required: true
          description: Identifiant unique de l'aéroport à supprimer.
          schema:
            type: integer
            example: 93999209
      responses:
        '200':
          description: L'aéroport a été supprimé avec succès.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "L'aéroport a été supprimé avec succès."
        '404':
          description: Aéroport non trouvé.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Aéroport non trouvé."
        '500':
          description: Requête invalide.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Requête invalide. Erreur retournée par le serveur : [message d'erreur]."
    put:
      summary: Mettre à jour un aéroport
      tags:
        - airports
      parameters:
        - in: path
          name: id
          required: true
          description: Identifiant unique de l'aéroport à mettre à jour.
          schema:
            type: integer
            example: 93999209
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                city:
                  type: string
                  description: Ville où se situe l'aéroport.
                  example: Washington
                state:
                  type: string
                  description: Code ISO 3166-2 (moins le préfixe « US- ») de l'état où se situe l'aéroport.
                  example: DC
                name:
                  type: string
                  description: Nom de l'aéroport.
                  example: Washington Airport
              required:
                - city
                - state
                - name
      responses:
        '200':
          description: L'aéroport a été mis à jour avec succès.
          content:
            application/json:
              schema:
                type: object
                properties:
                  city:
                    type: string
                    example: Washington
                  state:
                    type: string
                    example: DC
                  name:
                    type: string
                    example: Washington Airport
                  _id:
                    type: string
                    example: 5f7b3b7b7b7b7b7b7b7b7b7b
                  airport_id:
                    type: integer
                    example: 93999209
                  __v:
                    type: integer
                    example: 0
        '404':
          description: Aéroport non trouvé.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Aéroport non trouvé."
        '400':
          description: Requête invalide.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Requête invalide. Erreur retournée par le serveur : [message d'erreur]."
  /api/flights:
    get:
      summary: Récupérer la liste complète des vols
      tags:
        - flights
      responses:
        '200':
          description: Une liste de tous les vols enregistrés.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Flight'


components:
  schemas:
    Flight:
      type: object
      properties:
        _id:
          type: string
          description: ID du vol. Unique.
          example: "662a6d05a9206857001ad3da"
        carrier:
          type: string
          description: Nom de la compagnie aérienne.
          example: "DL"
        origin_id:
          type: integer
          format: int32
          description: ID de l'aéroport de départ
        destination_id:
          type: integer
          format: int3
          description: ID de l'aéroport d'arrivée
        date:
          type: string
          description: Date de départ du vol.
          example: "2025-03-23T23:00:00.000Z"
    Airport:
      type: object
      properties:
        airport_id:
          type: integer
          description: Identifiant unique de l'aéroport.
          example: 10165
        city:
          type: string
          description: Ville où se situe l'aéroport.
          example: Barrow
        state:
          type: string
          description: Code ISO 3166-2 (moins le préfixe US-) de l'état où se situe l'aéroport.
          example: AK
        name:
          type: string
          description: Nom de l'aéroport.
          example: Deadhorse Airport