openapi: 3.1.0
info:
  title: SkyHub API
  description: API permettant de récupérer diverses données sur l'aviation.
  version: 0.0.1
  license:
    name: MIT License
    url: https://opensource.org/licenses/MIT

tags:
    - name: flights
      description: Opérations liées aux vols

paths:
  /api/flights:
    get:
      tag:
        - flights
      summary: Récupère la liste des volss
      responses:
        '200':
          description: Une liste de tous les vols enregistrés.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Flight'

components:
  schemas:
    Flight:
      type: object
      properties:
        id:
          type: integer
          format: int32
          description: ID du vol. Unique.
          example: 1
        name:
          type: string
          description: Nom du vol.
          example: "AF123"