name: Publication sur Docker Hub

on:
  push:
    branches: [ master ]

jobs:
  build-and-push-api:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du dépôt
        uses: actions/checkout@v4

      - name: Compilation vers image Docker
        run: sudo docker build -t dimitridr/skyhub-server:$GITHUB_SHA -f docker/Dockerfile-skyhub-server .

      - name: Étiquetage « latest » sur image produite
        run: docker tag dimitridr/skyhub-server:$GITHUB_SHA dimitridr/skyhub-server:latest

      - name: Connexion à Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Publication sur Docker Hub (avec SHA GitHub)
        run: docker push dimitridr/skyhub-server:$GITHUB_SHA

      - name: Publication sur Docker Hub (latest)
        run: docker push dimitridr/skyhub-server:latest

  build-and-push-db:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout du dépôt
        uses: actions/checkout@v4

      # J'avais utilisé Git LFS qui était plus simple et pro que
      # cette méthode, mais le quota a été dépassé en deux commits...
      - name: Récupération du fichier flights.json
        uses: wei/wget@v1
        with:
          args: --no-check-certificate "https://drive.google.com/file/d/1F_5FZg5BaoLQErIKZ5S9b21AWc-1DIHc/view?usp=drive_link" -O db-files/flights.json

      - name: Compilation vers image Docker
        run: sudo docker build -t dimitridr/skyhub-db:$GITHUB_SHA -f docker/Dockerfile-skyhub-db .

      - name: Étiquetage « latest » sur image produite
        run: docker tag dimitridr/skyhub-db:$GITHUB_SHA dimitridr/skyhub-db:latest

      - name: Connexion à Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Publication sur Docker Hub (avec SHA GitHub)
        run: docker push dimitridr/skyhub-db:$GITHUB_SHA

      - name: Publication sur Docker Hub (latest)
        run: docker push dimitridr/skyhub-db:latest